# Configuration for spec plan planning flows
# Creating, reviewing, and refining specification plans before implementation

base_config: .flow/base.yaml
flow_type: plan

# Agent interface: claude_code_cli or opencode
agent_interface: opencode

# OpenCode-specific configuration
opencode:
  server_hostname: 127.0.0.1

# Spec plan parsing configuration
spec_plan:
  top_level_end_marker: "## Implementation Steps"
  step_header_pattern: "^### Status: ([^|]*) \\| Step (\\d+): (.+)$"

# Completion workflow configuration
completion_workflow:
  template: "@.flow/templates/planning-completion-workflow-template.md"
  report:
    filename: report.md
    success_suffix: .complete.md
    failure_suffix: .failed.md

# Shared files
shared_files:
  # Writable shared files - context that accumulates across agents in a flow
  planning_log:
    path: "{flow_dir}/{flow_name}/planning-log.md"
    info: "Accumulated planning decisions, clarifications, and context. Read this to understand planning context and decisions made."
    writable: true
    write_template: "@.flow/templates/planning-log-template.md"

  # Read-only shared files - architectural context for planning
  architecture_guide:
    path: "rules_and_guides/architecture-guide.md"
    info: "Layered architecture (types/lib/commands/interfaces), key files impact matrix. Essential for knowing WHERE things should go."
    agents:
      - plan-creator

  common_policies:
    path: "rules_and_guides/common-policies.md"
    info: "Architectural constraints: no legacy/backwards compatibility code, LSP compliance, no dual code paths. Plans must account for these rules."
    agents:
      - plan-creator

  code_duplication_rules:
    path: "rules_and_guides/code-duplication-rules.md"
    info: "Principle of reusing existing utilities from flow/lib/. Plans should direct to existing utilities rather than new implementations."
    agents:
      - plan-creator

  documentation_updates:
    path: "rules_and_guides/documentation_updates.md"
    info: "Documentation files that must be updated. Plans should include documentation update steps where relevant."
    agents:
      - plan-creator

  cli_patterns:
    path: "rules_and_guides/cli-patterns.md"
    info: "CLI patterns: Click command structure, shared argument handling, Rich/Textual output. Helps plan CLI feature organization."
    agents:
      - plan-creator

  test_patterns:
    path: "rules_and_guides/test-patterns.md"
    info: "Test organization: unit/integration/e2e categories, fixture patterns. Plans should specify appropriate test coverage."
    agents:
      - plan-creator

  uv_scripts:
    path: "rules_and_guides/uv-scripts.md"
    info: "UV inline script format (PEP 723) for standalone Python scripts. Plans involving scripts should account for this."
    agents:
      - plan-creator

  spec_anti_code_policy:
    path: "rules_and_guides/spec-anti-code-policy.md"
    info: "CRITICAL: Spec plans define WHAT to build, not HOW. No implementation code - only type signatures and labeled pseudo-code."
    agents:
      - plan-creator

# Agent definitions for planning flows
agents:
  plan-creator:
    description: "Creates spec plans defining WHAT to build."
    #model: anthropic/opus # Claude Code model ID
    model: anthropic/claude-haiku-4-5 # opencode model ID
    system_prompt: "@.claude/agents/plan-creator.md"
    mcp_config: .mcp-context7-2k.json
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/planning-log.md"
        append: true
        description: "Planning log entry"

  showcase-planner:
    description: "Creates showcase requirements for proof generation."
    #model: anthropic/sonnet # Claude Code model ID
    model: anthropic/claude-haiku-4-5 # opencode model ID
    system_prompt: "@.flow/proof/agents/showcase-planner.md"
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/planning-log.md"
        append: true
        description: "Planning log entry"
