# Configuration for proof generation flows
# Evidence collection, narrative generation, and fact-checking

base_config: .flow/base.yaml
flow_type: proof

# Agent interface: claude_code_cli or opencode
agent_interface: claude_code_cli

# OpenCode-specific configuration
opencode:
  server_hostname: 127.0.0.1

# Completion workflow configuration
completion_workflow:
  template: "@.flow/templates/completion-workflow-template.md"
  report:
    filename: report.md
    success_suffix: .complete.md
    failure_suffix: .failed.md

# Agent definitions for proof generation
# Note: Evidence collection is now done deterministically in Python code
# (proof_runner.collect_evidence), so no evidence-collector agent is needed.
agents:
  showcase-planner:
    model: anthropic/sonnet
    system_prompt: "@.flow/proof/agents/showcase-planner.md"

  narrative-writer:
    model: anthropic/sonnet
    system_prompt: "@.flow/proof/agents/narrative-writer.md"

  fact-checker:
    model: anthropic/sonnet
    system_prompt: "@.flow/proof/agents/fact-checker.md"
