# Base configuration for implement flows
# Feature implementation, bug fixes, refactoring, etc.

base_config: .flow/base.yaml
flow_type: implement

# Agent interface: claude_code_cli or opencode
agent_interface: claude_code_cli

# OpenCode-specific configuration (when using agent_interface: opencode)
opencode:
  server_hostname: 127.0.0.1

# Spec plan parsing configuration
spec_plan:
  top_level_end_marker: "## Implementation Steps"
  step_header_pattern: "^### Status: ([^|]*) \\| Step (\\d+): (.+)$"

# Completion workflow configuration
completion_workflow:
  template: "@.flow/templates/implementation-completion-workflow-template.md"
  report:
    filename: report.md
    success_suffix: .complete.md
    failure_suffix: .failed.md

# Shared files
shared_files:
  # Writable shared files - context that accumulates across agents in a flow
  implementation_log:
    path: "{flow_dir}/{flow_name}/implementation-log.md"
    info: "Accumulated decisions, patterns, and context from previous steps. Read this to understand what has been done and follow established patterns."
    writable: true
    write_template: "@.flow/templates/implementation-log-template.md"

  # Read-only shared files - agent instructions - guaranteed to be in system prompt for relevant agents
  common_policies:
    path: "rules_and_guides/common-policies.md"
    info: "Project-wide policies including rules and package manager usage."
    agents:
      - builder
      - reviewer

  architecture_guide:
    path: "rules_and_guides/architecture-guide.md"
    info: "Layered architecture (types/lib/commands/interfaces), key files impact matrix, and documentation update checklists."
    agents:
      - builder
      - reviewer
      - documentation-updater
      - documentation-reviewer

  cross_platform_rules:
    path: "rules_and_guides/cross-platform-rules.md"
    info: "CRITICAL cross-platform compatibility rules: file encoding (UTF-8), path handling (pathlib), subprocess (no shell=True)."
    agents:
      - builder
      - reviewer

  documentation_updates:
    path: "rules_and_guides/documentation_updates.md"
    info: "Documentation update requirements. Lists documentation files to keep current and when updates are required."
    agents:
      - builder
      - reviewer
      - documentation-updater
      - documentation-reviewer

  python_code_quality:
    path: "rules_and_guides/python-code-quality.md"
    info: "Python code quality rules: security (YAML, subprocess), type safety, anti-patterns (bare except, mutable defaults), Pydantic patterns."
    agents:
      - builder
      - reviewer

  cli_patterns:
    path: "rules_and_guides/cli-patterns.md"
    info: "CLI patterns: Click command structure, option naming, Rich/Textual output, exit codes, UX checklist."
    agents:
      - builder
      - reviewer

  context7_usage:
    path: "rules_and_guides/context7-usage.md"
    info: "Context7 library documentation lookup: pyproject.toml as source of truth, how to verify library usage against specific versions."
    agents:
      - builder
      - reviewer

  code_duplication_rules:
    path: "rules_and_guides/code-duplication-rules.md"
    info: "Code duplication detection rules: mandatory search process, common patterns table, enforcement rules."
    agents:
      - builder
      - reviewer

  test_patterns:
    path: "rules_and_guides/test-patterns.md"
    info: "Pytest patterns: fixtures, test class organization, Click CLI testing with CliRunner, assertions."
    agents:
      - builder
      - reviewer

  uv_scripts:
    path: "rules_and_guides/uv-scripts.md"
    info: "UV inline script format (PEP 723) rules for standalone Python scripts."
    agents:
      - builder
      - reviewer

# Agent definitions for implement flows
agents:
  builder:
    description: "Implements code changes following the spec plan. The reviewer validates your work."
    model: anthropic/opus
    system_prompt: "@.claude/agents/builder.md"
    mcp_config: .mcp-context7-2k.json
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry"

  reviewer:
    description: "Validates code changes (read-only review). Never modifies source files directly."
    model: anthropic/opus
    system_prompt: "@.claude/agents/reviewer.md"
    mcp_config: .mcp-context7-2k.json
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry"

  documentation-updater:
    description: "Updates documentation to reflect code changes."
    model: anthropic/opus
    system_prompt: "@.claude/agents/documentation-updater.md"
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry"

  documentation-reviewer:
    description: "Validates documentation changes (read-only). Does not make documentation changes."
    model: anthropic/sonnet
    system_prompt: "@.claude/agents/documentation-reviewer.md"
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry"

  smoketester:
    description: "Runs smoke tests to validate completed implementation flows."
    model: anthropic/sonnet
    system_prompt: "@.claude/agents/smoketester.md"
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry"
