# Implement flow configuration for TestPods
# Takes a spec plan and implements it step by step

base_config: .flow/base.yaml
flow_type: implement
agent_interface: claude_code_cli

# Spec plan parsing configuration
spec_plan:
  top_level_end_marker: "## Implementation Steps"
  step_header_pattern: "^### Status: ([^|]*) \\| Step (\\d+): (.+)$"

# Completion workflow configuration
completion_workflow:
  template: "@.flow/templates/implementation-completion-workflow-template.md"
  report:
    filename: report.md
    success_suffix: .complete.md
    failure_suffix: .failed.md

# Agent definitions
agents:
  builder:
    model: anthropic/opus
    system_prompt: "@.claude/agents/builder.md"
    description: "Implements code changes following the spec plan. The reviewer validates your work."
    declared_artifacts:
      - type: log_entry
        path: "{flow_dir}/{flow_name}/implementation-log.md"
        append: true
        description: "Implementation log entry documenting decisions and progress"

  reviewer:
    model: anthropic/opus
    system_prompt: "@.claude/agents/reviewer.md"
    description: "Validates code changes (read-only review). Approves or requests changes."

# Shared files across agents
shared_files:
  implementation_log:
    path: "{flow_dir}/{flow_name}/implementation-log.md"
    info: "Accumulated decisions and context from previous steps."
    writable: true
    write_template: "@.flow/templates/implementation-log-template.md"

  refactor_docs:
    path: "specs/refactorings/REFACTORINGS_README.md"
    info: "Refactoring plan tasks."
    agents:
      - builder
      - reviewer

#  prd_docs:
#    path: "prd"
#    info: "Product documentation for TestPods."
#    agents:
#      - builder
#      - reviewer

#  specs_docs:
#    path: "specs"
#    info: "Development specifications and refactoring plans."
#    agents:
#      - builder
#      - reviewer
