# Plan flow configuration for TestPods
# Takes a feature request and creates a spec plan

base_config: .flow/base.yaml
flow_type: plan
agent_interface: claude_code_cli

# Completion workflow configuration
completion_workflow:
  template: "@.flow/templates/planning-completion-workflow-template.md"
  report:
    filename: report.md
    success_suffix: .complete.md
    failure_suffix: .failed.md

# Agent definitions
agents:
  planner:
    model: anthropic/opus
    system_prompt: "@.claude/agents/planner.md"
    description: "Creates detailed implementation plans from feature requests."
    declared_artifacts:
      - type: spec_plan
        path: "{flow_dir}/{flow_name}/spec-plan.md"
        description: "The generated spec plan document"
      - type: log_entry
        path: "{flow_dir}/{flow_name}/planning-log.md"
        append: true
        description: "Planning log entry documenting research and decisions"

# Shared files
shared_files:
  planning_log:
    path: "{flow_dir}/{flow_name}/planning-log.md"
    info: "Planning decisions and research notes."
    writable: true
    write_template: "@.flow/templates/planning-log-template.md"

  refactor_docs:
    path: "specs/refactorings/REFACTORINGS_README.md"
    info: "Refactoring plan tasks."
    agents:
      - builder
      - reviewer

#  prd_docs:
#    path: "prd"
#    info: "Product documentation for TestPods."
#
#  specs_docs:
#    path: "specs"
#    info: "Development specifications and existing refactoring plans."
